spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
    #url: jdbc:mysql://localhost:3306/dbname
    #username: root
    #password:
    #driver-class-name: com.mysql.cj.jdbc.Driver